### ISSUE TITLE
can't run the evaluate code or train code 

### ISSUE THREAD

**Issue by hahawhat-ch** [dsshim0125/grmc#1]
Hi,excuse me,I already download the models in checkpoint ,but can't  run the" python evaluate_pytorch.py --model_type --layers"
 It's turns out"usage: evaluate_pytorch.py [-h] [--model_type MODEL_TYPE] [--layers LAYERS]
evaluate_pytorch.py: error: argument --model_type: expected one argument"
it would be great you can tell me how to deal with it.I'm new in this field,Thank u.

**Comment by dsshim0125** [comment]
As the argparse from Python requires a specific values to set the variables in the terminal, you should put some values in parsers like ( python evaluate_pytorch.py --model_type=densedepth --layers=161). We provide two pretrained depth estimation models which are densedepth with layers 161 and fcrn with layers 50. If you want to evaluate model in fcrn, please put model_type as fcrn and layers as 50.
